export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const CREATE_CODE = "CREATE_CODE";
export const UPDATE_CODE = "UPDATE_CODE";
export const DELETE_CODE = "DELETE_CODE";
export const GET_CODES = "GET_CODES";
export const CODES_LOADING = "CODES_LOADING";

export const UPDATE_USER = "UPDATE_USER";
export const GET_USERS = "GET_USERS";
export const USERS_LOADING = "USERS_LOADING";

export const GET_MACHINES = "GET_MACHINES";
export const CREATE_MACHINE = "CREATE_MACHINE";
export const UPDATE_MACHINE = "UPDATE_MACHINE";
export const DELETE_MACHINE = "DELETE_MACHINE";
export const MACHINES_LOADING = "MACHINES_LOADING";